// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	dao "MockTest/pkg/user/dao"

	mock "github.com/stretchr/testify/mock"
)

// UserDao is an autogenerated mock type for the UserDao type
type UserDao struct {
	mock.Mock
}

// GetUserByMobile provides a mock function with given fields: ctx, mobile
func (_m *UserDao) GetUserByMobile(ctx context.Context, mobile string) (*dao.User, error) {
	ret := _m.Called(ctx, mobile)

	var r0 *dao.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *dao.User); ok {
		r0 = rf(ctx, mobile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mobile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}