// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	dao "MockTest/internal/user/dao"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserDao is an autogenerated mock type for the UserDao type
type UserDao struct {
	mock.Mock
}

// GetUserByMobile provides a mock function with given fields: ctx, mobile
func (_m *UserDao) GetUserByMobile(ctx context.Context, mobile string) (*dao.User, error) {
	ret := _m.Called(ctx, mobile)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByMobile")
	}

	var r0 *dao.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*dao.User, error)); ok {
		return rf(ctx, mobile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *dao.User); ok {
		r0 = rf(ctx, mobile)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, mobile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserDao creates a new instance of UserDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserDao {
	mock := &UserDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
